// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Organization.Infrastructure.Persistance.Context;

#nullable disable

namespace Organization.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260314154601_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Organization.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerOrganizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SellerOrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuyerOrganizationId");

                    b.HasIndex("SellerOrganizationId");

                    b.ToTable("order", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("orderitem", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproval")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("organization", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.OrganizationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organizationuser", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsStock")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("RatingId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RatingId");

                    b.ToTable("product", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("rating", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.RatingCommentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentary")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreateAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("ratingcommentary", "organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.Order", b =>
                {
                    b.HasOne("Organization.Domain.Models.Organization", "BuyerOrganization")
                        .WithMany()
                        .HasForeignKey("BuyerOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organization.Domain.Models.Organization", "SellerOrganization")
                        .WithMany()
                        .HasForeignKey("SellerOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyerOrganization");

                    b.Navigation("SellerOrganization");
                });

            modelBuilder.Entity("Organization.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("Organization.Domain.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Organization.Domain.Models.Price", "PriceUnit", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("integer");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("orderitem", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.OwnsOne("Organization.Domain.Models.Price", "TotalPrice", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("integer");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("orderitem", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("Order");

                    b.Navigation("PriceUnit")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Organization.Domain.Models.Organization", b =>
                {
                    b.OwnsOne("Organization.Domain.ValueObjects.Address", "LegalAddress", b1 =>
                        {
                            b1.Property<int>("OrganizationId")
                                .HasColumnType("integer");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organization", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("Organization.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("OrganizationId")
                                .HasColumnType("integer");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organization", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LegalAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Organization.Domain.Models.OrganizationUser", b =>
                {
                    b.HasOne("Organization.Domain.Models.Organization", "Organization")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Organization.Domain.Models.Product", b =>
                {
                    b.HasOne("Organization.Domain.Models.Organization", "Organization")
                        .WithMany("Products")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Organization.Domain.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId");

                    b.OwnsOne("Organization.Domain.Models.Price", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.HasKey("ProductId");

                            b1.ToTable("product", "organization");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Organization");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Organization.Domain.Models.Rating", b =>
                {
                    b.OwnsOne("Organization.Domain.ValueObjects.RatingValue", "AvgValue", b1 =>
                        {
                            b1.Property<int>("RatingId")
                                .HasColumnType("integer");

                            b1.HasKey("RatingId");

                            b1.ToTable("rating", "organization");

                            b1.WithOwner()
                                .HasForeignKey("RatingId");
                        });

                    b.Navigation("AvgValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Organization.Domain.Models.RatingCommentary", b =>
                {
                    b.HasOne("Organization.Domain.Models.Rating", "Rating")
                        .WithMany("Commentaries")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Organization.Domain.ValueObjects.RatingValue", "RatingValue", b1 =>
                        {
                            b1.Property<int>("RatingCommentaryId")
                                .HasColumnType("integer");

                            b1.HasKey("RatingCommentaryId");

                            b1.ToTable("ratingcommentary", "organization");

                            b1.WithOwner()
                                .HasForeignKey("RatingCommentaryId");
                        });

                    b.Navigation("Rating");

                    b.Navigation("RatingValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Organization.Domain.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Organization.Domain.Models.Organization", b =>
                {
                    b.Navigation("OrganizationUsers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Organization.Domain.Models.Rating", b =>
                {
                    b.Navigation("Commentaries");
                });
#pragma warning restore 612, 618
        }
    }
}
